/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AufgabenRouteImport } from './routes/aufgaben'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as FotosRouteImport } from './routes/fotos'
import { Route as WaterPlantsRouteImport } from './routes/waterPlants'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AufgabenRoute = AufgabenRouteImport.update({
  id: '/aufgaben',
  path: '/aufgaben',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosRoute = FotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const WaterPlantsRoute = WaterPlantsRouteImport.update({
  id: '/waterPlants',
  path: '/waterPlants',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aufgaben': typeof AufgabenRoute
  '/expenses': typeof ExpensesRoute
  '/fotos': typeof FotosRoute
  '/waterPlants': typeof WaterPlantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aufgaben': typeof AufgabenRoute
  '/expenses': typeof ExpensesRoute
  '/fotos': typeof FotosRoute
  '/waterPlants': typeof WaterPlantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aufgaben': typeof AufgabenRoute
  '/expenses': typeof ExpensesRoute
  '/fotos': typeof FotosRoute
  '/waterPlants': typeof WaterPlantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aufgaben' | '/expenses' | '/fotos' | '/waterPlants'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aufgaben' | '/expenses' | '/fotos' | '/waterPlants'
  id: '__root__' | '/' | '/aufgaben' | '/expenses' | '/fotos' | '/waterPlants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AufgabenRoute: typeof AufgabenRoute
  ExpensesRoute: typeof ExpensesRoute
  FotosRoute: typeof FotosRoute
  WaterPlantsRoute: typeof WaterPlantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aufgaben': {
      id: '/aufgaben'
      path: '/aufgaben'
      fullPath: '/aufgaben'
      preLoaderRoute: typeof AufgabenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos': {
      id: '/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof FotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waterPlants': {
      id: '/waterPlants'
      path: '/waterPlants'
      fullPath: '/waterPlants'
      preLoaderRoute: typeof WaterPlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AufgabenRoute: AufgabenRoute,
  ExpensesRoute: ExpensesRoute,
  FotosRoute: FotosRoute,
  WaterPlantsRoute: WaterPlantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
