/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterPlantsRouteImport } from './routes/waterPlants'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FotosRouteImport } from './routes/fotos'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as AufgabenRouteImport } from './routes/aufgaben'
import { Route as IndexRouteImport } from './routes/index'

const WaterPlantsRoute = WaterPlantsRouteImport.update({
  id: '/waterPlants',
  path: '/waterPlants',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosRoute = FotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AufgabenRoute = AufgabenRouteImport.update({
  id: '/aufgaben',
  path: '/aufgaben',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aufgaben': typeof AufgabenRoute
  '/expenses': typeof ExpensesRoute
  '/fotos': typeof FotosRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/waterPlants': typeof WaterPlantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aufgaben': typeof AufgabenRoute
  '/expenses': typeof ExpensesRoute
  '/fotos': typeof FotosRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/waterPlants': typeof WaterPlantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aufgaben': typeof AufgabenRoute
  '/expenses': typeof ExpensesRoute
  '/fotos': typeof FotosRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/waterPlants': typeof WaterPlantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aufgaben'
    | '/expenses'
    | '/fotos'
    | '/login'
    | '/setup'
    | '/waterPlants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aufgaben'
    | '/expenses'
    | '/fotos'
    | '/login'
    | '/setup'
    | '/waterPlants'
  id:
    | '__root__'
    | '/'
    | '/aufgaben'
    | '/expenses'
    | '/fotos'
    | '/login'
    | '/setup'
    | '/waterPlants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AufgabenRoute: typeof AufgabenRoute
  ExpensesRoute: typeof ExpensesRoute
  FotosRoute: typeof FotosRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  WaterPlantsRoute: typeof WaterPlantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waterPlants': {
      id: '/waterPlants'
      path: '/waterPlants'
      fullPath: '/waterPlants'
      preLoaderRoute: typeof WaterPlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos': {
      id: '/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof FotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aufgaben': {
      id: '/aufgaben'
      path: '/aufgaben'
      fullPath: '/aufgaben'
      preLoaderRoute: typeof AufgabenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AufgabenRoute: AufgabenRoute,
  ExpensesRoute: ExpensesRoute,
  FotosRoute: FotosRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  WaterPlantsRoute: WaterPlantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
