/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaterPlantsRouteImport } from './routes/waterPlants'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CreateExpenseRouteImport } from './routes/create-expense'
import { Route as IndexRouteImport } from './routes/index'

const WaterPlantsRoute = WaterPlantsRouteImport.update({
  id: '/waterPlants',
  path: '/waterPlants',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateExpenseRoute = CreateExpenseRouteImport.update({
  id: '/create-expense',
  path: '/create-expense',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-expense': typeof CreateExpenseRoute
  '/expenses': typeof ExpensesRoute
  '/waterPlants': typeof WaterPlantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-expense': typeof CreateExpenseRoute
  '/expenses': typeof ExpensesRoute
  '/waterPlants': typeof WaterPlantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-expense': typeof CreateExpenseRoute
  '/expenses': typeof ExpensesRoute
  '/waterPlants': typeof WaterPlantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-expense' | '/expenses' | '/waterPlants'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-expense' | '/expenses' | '/waterPlants'
  id: '__root__' | '/' | '/create-expense' | '/expenses' | '/waterPlants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateExpenseRoute: typeof CreateExpenseRoute
  ExpensesRoute: typeof ExpensesRoute
  WaterPlantsRoute: typeof WaterPlantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waterPlants': {
      id: '/waterPlants'
      path: '/waterPlants'
      fullPath: '/waterPlants'
      preLoaderRoute: typeof WaterPlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-expense': {
      id: '/create-expense'
      path: '/create-expense'
      fullPath: '/create-expense'
      preLoaderRoute: typeof CreateExpenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateExpenseRoute: CreateExpenseRoute,
  ExpensesRoute: ExpensesRoute,
  WaterPlantsRoute: WaterPlantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
